name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run check-types
      - run: npm run lint
      - run: npm test

      - name: Package extension
        run: npx vsce package --out vscode-function-starlark.vsix

      - name: Upload .vsix to GitHub Release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2
        with:
          files: vscode-function-starlark.vsix
